package:
  name: scicone
  version: '0.0.1'

source:
  git_url: https://github.com/amcpherson/SCICoNE.git
  git_rev: 5e3420a0204a8b76f3ffdfa64671777b5d89c8b6

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.19.7
    - boost >=1.75.0
    - openmp >=8.0.1
    - nlopt >=2.6.2
  
  run:
    - boost >=1.75.0
    - openmp >=8.0.1
    - nlopt >=2.6.2

about:
  home: https://github.com/cbg-ethz/SCICoNE
  license: GPLv3
  summary: 'Single-cell copy number calling and event history reconstruction'

